language: ruby
sudo: false
cache:
  bundler: true
rvm:
 - '2.4.2'
script:
  - bundle exec ruby spec/test_server.rb &
  - sleep 5
  - bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: always
